[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2859df"
backgroundColor = "#f6f8fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#14213b"
font = "sans serif"
